### ISSUE TITLE
Gradle 8 support

### ISSUE THREAD

**Issue by jaygeoguy** [levibostian/dotenv-android#30]
Hi @levibostian , I was curious if added mac support was on the roadmap for this library. 

> It looks like the Gradle plugin does not support your computer. Please, file an issue: https://github.com/levibostian/dotenv-android/issues/new with the full stacktrace. OS name: mac os x, Arch: aarch64

> Task :app:generateDebugDotenv FAILED
=== dotenv-android plugin running ===
dotenv-android info:
dotenv CLI compatible version: >= 1.1.0 && < 2
downloading CLI dependency...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 9 executed
/Library/Ruby/Gems/2.6.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:25:in `exec': No such file or directory - version (Errno::ENOENT)
	from /Library/Ruby/Gems/2.6.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:25:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/dotenv-2.7.6/bin/dotenv:4:in `<top (required)>'
	from /usr/local/bin/dotenv:23:in `load'
	from /usr/local/bin/dotenv:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:25:in `exec': No such file or directory - version (Errno::ENOENT)
	from /Library/Ruby/Gems/2.6.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:25:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/dotenv-2.7.6/bin/dotenv:4:in `<top (required)>'
	from /usr/local/bin/dotenv:23:in `load'
	from /usr/local/bin/dotenv:23:in `<main>'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugDotenv'.
> It looks like the Gradle plugin does not support your computer. Please, file an issue: https://github.com/levibostian/dotenv-android/issues/new with the full stacktrace. OS name: mac os x, Arch: aarch64

**Comment by levibostian** [comment]
Thanks for reporting this. I appreciate it. 

This project does have mac support already. It looks like you're running gradle 8 and the error your getting is the plugin is saying it's not compatible with gradle 8. 

I am not very familiar with gradle 8 and how much changed from 7. So I don't have a timeline for when I would get to doing this. 

Any help would be appreciated from someone. If it was me, I would start with these steps:
* Get [development environment setup](https://github.com/levibostian/dotenv-android?tab=readme-ov-file#development) for this plugin. 
* Upgrade the `androidApp/` to gradle 8. 
* In the `androidApp/` app, reproduce this error above. 
* Run `:app:generateDebugDotenv` command with added `--warning-mode all` to get all of the deprecation warnings that need fixed. 
* Go into the gradle plugin and fix whatever warnings were printed above. 

Happy to help anyone as they work through this.
